export const state = {
  G: {},
  selectedAcademy: null,
  currentChoices: [],
  transferOffers: [],
  rcOffer: null,
  renewalOffer: null,
  renewalContext: null,
  renewalCheckSeason: null,
  freeAgentRenewalCheckSeason: null,
  pendingSeason: null,
  seasonAction: 1,
  seasonActionsTotal: 10,
  actionLocked: false,
};
