export const state = {
  G: {},
  statFeedback: {},
  selectedAcademy: null,
  academyChoices: [],
  currentChoices: [],
  transferOffers: [],
  rcOffer: null,
  renewalOffer: null,
  renewalContext: null,
  renewalCheckSeason: null,
  freeAgentRenewalCheckSeason: null,
  pendingContract: null,
  pendingTransfer: null,
  pendingSeason: null,
  marketBoard: null,
  loanSignOffer: null,
  pendingLoanReaction: null,
  marketApplications: [],
  marketFeedbackQueue: [],
  marketLastResponseSeason: null,
  marketUi: {
    incomingIndex: null,
    targetIndex: null,
    applyMode: 'balanced',
  },
  extensionUi: {
    mode: 'balanced',
    lastFeedback: '',
  },
  preseasonCup: null,
  seasonAction: 1,
  seasonActionsTotal: 10,
  actionLocked: false,
};
